use_frameworks!

platform:ios, '9.0'
inhibit_all_warnings!

target 'AnnotationTextIOS_Example' do
  pod 'AnnotationTextIOS', :path => '../'

  target 'AnnotationTextIOS_Tests' do
    inherit! :search_paths

    
  end
end
